config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'

  root to: 'games#new'
  resources :games, only: [:new, :create]
  resources :guesses
  resources :identifications do
    resources :guesses
  end
  resources :cohorts
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/census_user.rb
class CensusUser

  attr_reader :first_name, :image_url

  def initialize(user_attributes)
    @first_name = user_attributes["first_name"]
    @image_url = user_attributes["image_url"]
  end

end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :people
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :identification

  def correct?
    hypothesis == identification.person.first_name
  end
end

app/models/identification.rb
class Identification < ApplicationRecord
  belongs_to :person
  has_many :guesses

  def possibilities(cohort)
    possibilities = [person] + (cohort.people - [person]).shuffle.last(3)
    possibilities.shuffle
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :cohort
  has_many :identifications

  def self.new_game
    person = Person.new
    person.clear_all_people
    person.load_people
  end

  def self.random
    random_set(1).first
  end

  def self.random_set(quantity)
    limit(quantity).order("RANDOM()")
  end

  def self.random_person_with_image
    where.not(photo_url: "https://turing-census.herokuapp.com/images/original/missing.png").order("RANDOM()").limit(1)
  end

  def clear_all_people
    Person.destroy_all
  end

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_cohort

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_cohort
    @current_cohort ||= Cohort.find(session[:cohort_id]) if session[:cohort_id]
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def index
    @cohorts = Cohort.all
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create
    clear_all_people
    people_info = CensusApiService.fetch_people(current_user.access_token)
    CensusApiService.load_people(people_info)
    redirect_to cohorts_path
  end

  private

  def clear_all_people
    Person.destroy_all
  end

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def new
    @identification = Identification.find(params[:identification_id])
    @guess = @identification.guesses.new
  end

  def create
    @identification = Identification.find(params[:identification_id])
    @guess = @identification.guesses.create(:hypothesis => params[:name])

    if @guess.correct?
      flash[:success] = "Correct: #{params[:name]}!"
      redirect_to new_identification_path
    else
      flash[:error] = "You guessed #{params[:name]} but this is #{@identification.person.first_name}"
      redirect_to new_identification_guess_path(:identification => @identification)
    end
  end
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  def new
    if params[:cohort_id]
      cohort = Cohort.find(params[:cohort_id])
      session[:cohort_id] = cohort.id
    else
      cohort = current_cohort
    end
    users = cohort.people
    @identification = Identification.create(:person => users.random_person_with_image[0])
    redirect_to new_identification_guess_path(@identification)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    census_user_info = env["omniauth.auth"]
    user = User.find_or_create_by(census_id: census_user_info.info.id)
    user.update_attributes(first_name: census_user_info.info.first_name,
                           last_name: census_user_info.info.last_name,
                           access_token: census_user_info.info.token)

    session[:user_id] = user.id
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cohorts/index.html.erb
Select a Cohort:

<%= form_tag new_identification_path, method: 'get' do  %>
  <%= select_tag :cohort_id, options_from_collection_for_select(@cohorts, "id", "name") %>
  <%= submit_tag "Play Game!" %>
<% end  %>

app/views/games/new.html.erb
<h2>Welcome to Yearbook!</h2>
<h3>Start a new game</h3>

<% unless current_user %>
  <%= button_to 'Login with Census', '/auth/census', method: 'get' %>
<% end %>

<%= button_to 'Start Game', games_path %>

app/views/guesses/new.html.erb
<section class="photo-content">
  <% if @identification.person.photo_url %>
  <div id='photo'>
    <%= image_tag @identification.person.photo_url %>
  </div>
  <% end %>
  <ul id='possibilities'>
    <% @identification.possibilities(current_cohort).each do |person| %>
    <li><%= link_to person.first_name, identification_guesses_path(@identification, :name => person.first_name), :method => :post, class:"guess-tab" %></li>
    <% end %>
  </ul>
</section>

<p id='answer'><%= @identification.person.first_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yearbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="content">
      <h1><%= link_to "Turing Yearbook", root_path %></h1>

      <%= render partial: "partials/flash_messages" %>

      <section class="yield-content">
        <%= yield %>
      </section>

    </section>
  </body>
</html>

app/views/partials/_flash_messages.html.erb
<div class="flash-container">
  <% if flash[:success] %>
    <p class="flash" id='flash-success'>
      <%= flash[:success] %>
    </p>
  <% end %>
  <% if %>
    <p class="flash" id="flash-error">
      <%= flash[:error] %>
    </p>
  <% end %>
</div>